# Eléments de symmétrie du cristal de $Sr_2NCl$ 


In [262]:
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from mp_api.client import MPRester
from jupyter_jsmol.pymatgen import quick_view
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol import JsmolView
from ipywidgets import Layout, widgets, interact
from IPython.display import display

In [263]:
mp_key ="iX81lxwugQ7QfGznstwLyMrndo3WUZbE"
mp_id = "mp-23033"

with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure() # maille conventionnelle
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations() #ensemble des opérations de symétries

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

## 1. Introduction
Ce notebook nous permettra d'analyser et de visualiser trois éléments de symétries du cristal de $Sr_2NCl$ formé par une maille trigonale rhomboédrique.  

Ce cristal fait partie du groupe d’espace $R\bar{3}m$ et contient 36 éléments de symétries.  

Pour faciliter la visualisation, les transformations seront représentées dans la maille conventionnelle.

Les atomes subbissant la transformation seront marqué d'un repère et les flèches de transformations seront appliquées dessus. Les transformations peuvent sortir de la maille mais l'atome équivalent dans celle-ci sera lui aussi marqué d'un repère.



In [264]:
print( "Groupe d'espace   : " , symmops,"\n")
print("Nombre de symmétrie : " , len(symmops),"\n")


Groupe d'espace   :  R-3m (166) spacegroup 

Nombre de symmétrie :  36 



## 2.Rotation

In [266]:

i_atom = 27
i_symmop = 10
symmop = symmops[i_symmop]
print(symmop)
print("\n")



pos_init = conv_struc.sites[7].frac_coords
pos_final = symmop.operate(pos_init)
print("Position initiale de l'atome : " + str(pos_init))
print("Position finale de l'atome : " + str(pos_final))

conv_view = quick_view(conv_struc, "packed", conventional = True)
display(conv_view)


conv_view.script('select strontium; color lightblue')
conv_view.script('select nitrogen; color lightgreen')
conv_view.script('select chlorine; color orange')

conv_view.script('draw SYMOP ' + str(i_symmop + 1) + ' {atomno = ' + str(i_atom) + '}')


Rot:
[[-1.  0.  0.]
 [-1.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


Position initiale de l'atome : [1.  1.  0.5]
Position finale de l'atome : [-1.00000000e+00 -1.11022302e-16 -5.00000000e-01]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Commentaire : 

On observe une symétrie de rotation d'ordre 2 ($C_2$).  

En effet, $\tau$, la matrice de translation, est nulle, indiquant une symétrie ponctuelle.  

Ensuite, posons $R$ comme la matrice de rotation. Son déterminant, qui vaut 1, nous indique que c'est une transformation de première espèce, n'inversant pas la chiralité. De plus, puisque $R^2 = I$, avec $I$ la matrice identité, appliquer deux fois la rotation revient à l'opération neutre. Nous avons donc un axe d'ordre 2.  

Enfin, l'axe de rotation est $[0 \ 1 \ 0]$.

## 3. Rotoinversion

In [288]:
i_atom= 10
i_symmop = 3
symmop = symmops[i_symmop]
print(symmop)
print("\n")


pos_init = conv_struc.sites[5].frac_coords
pos_final = symmop.operate(pos_init)
print("Position initiale de l'atome : " + str(pos_init))
print("Position finale de l'atome : " + str(pos_final))

conv_view = quick_view(conv_struc, "packed", conventional = True)
display(conv_view)


conv_view.script('select strontium; color lightblue')
conv_view.script('select nitrogen; color lightgreen')
conv_view.script('select chlorine; color orange')

conv_view.script('draw SYMOP ' + str(i_symmop + 1) + ' {atomno = ' + str(i_atom) + '}')

Rot:
[[ 0.  1.  0.]
 [-1.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


Position initiale de l'atome : [0.33333333 0.66666667 0.89706801]
Position finale de l'atome : [ 0.66666667  0.33333333 -0.89706801]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Commentaire : 

On observe une symétrie de roto-inversion d'ordre 3 ($\bar{C_3}$).  

Tout d'abord, la matrice de translation nulle indique une symétrie ponctuelle.  

Ensuite, le déterminant, qui vaut $-1$, témoigne de la symétrie d'inversion. C'est une opération de seconde espèce qui inverse la chiralité.  

De plus, si nous décomposons la matrice de roto-inversion comme suit :  
$$\mathbf{A} = -\mathbf{I} \cdot \mathbf{R}$$  
avec $\mathbf{I}$ la matrice identité et $\mathbf{R}$ la matrice de rotation, on a :  
$$\mathbf{R}^3 = \mathbf{I}.$$  
On a donc un axe d'ordre 3.  

Enfin, l'axe de rotation est : $[0 \ 0 \ 1].$ 

## 4. Symmétrie spatiale

In [296]:
i_atom= 3
i_symmop = 22
symmop = symmops[i_symmop]
print(symmop)
print("\n")

pos_init = conv_struc.sites[9].frac_coords
pos_final = symmop.operate(pos_init)
print("Position initiale de l'atome : " + str(pos_init))
print("Position finale de l'atome : " + str(pos_final))

conv_view = quick_view(conv_struc, "packed", conventional = True)
display(conv_view)


conv_view.script('select strontium; color lightblue')
conv_view.script('select nitrogen; color lightgreen')
conv_view.script('select chlorine; color orange')

conv_view.script('draw SYMOP ' + str(i_symmop+1 ) + ' {atomno = ' + str(i_atom) + '}')

Rot:
[[-1.  0.  0.]
 [-1.  1.  0.]
 [ 0.  0. -1.]]
tau
[0.66666667 0.33333333 0.33333333]


Position initiale de l'atome : [0. 0. 0.]
Position finale de l'atome : [0.66666667 0.33333333 0.33333333]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Commentaire : 

On observe que la matrice de translation est non nulle. Nous avons donc une symétrie spatiale.

De la même manière que précédemment, nous pouvons analyser la matrice de rotation. Nous en déduisons qu'elle décrit une rotation d'ordre 2 autour de l'axe $[010]$.

Nous remarquons que l'axe de rotation n'est pas parallèle à l'axe de translation $[\frac{2}{3} \ \frac{1}{3} \ \frac{1}{3}]$. Nous n'avons donc pas de rotation hélicoïdale. Nous avons juste une combinaison de rotation et de translation.
